### ISSUE TITLE
Do not have 'c' in MSCOCO annot

### ISSUE THREAD

**Issue by Cardinal2376** [mks0601/3DMPPE_ROOTNET_RELEASE#21]
Hi, it seems I do not have 'c' in the key of MSCOCO 2017 annotations. Could you help me with this problem?
Traceback (most recent call last):
  File "/home/workspace/code/3DMPPE_ROOTNET/main/test.py", line 60, in <module>
    main()
  File "/home/workspace/code/3DMPPE_ROOTNET/main/test.py", line 56, in main
    tester._evaluate(preds, cfg.result_dir)    
  File "/home/workspace/code/3DMPPE_ROOTNET/common/base.py", line 172, in _evaluate
    self.testset.evaluate(preds, result_save_path)
  File "/home/workspace/code/3DMPPE_ROOTNET/data/MSCOCO/MSCOCO.py", line 96, in evaluate
    c = gt['c']
KeyError: 'c'

**Comment by mks0601** [comment]
Sorry I added it at [here](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE/blob/b386e2d5fccd9384fe85edd2e48635ccf3f294d4/data/MSCOCO/MSCOCO.py#L76) and pushed this commit.

**Comment by Cardinal2376** [comment]
It solved my problem, thanks!
